cluster:
  mkdir -p logs/{rule}/ &&
  sbatch
    --parsable
    --cpus-per-task={threads}
    --time={resources.time}
    --job-name=smk-{rule}
    --output=logs/{rule}/{jobid}.out
    --error=logs/{rule}/{jobid}.err
    --partition={resources.partition}
default-resources:
  - time=1440
  - partition='compute-small'
  - tmpdir='/scratch'
jobs: 150
latency-wait: 120
local-cores: 1
restart-times: 1
max-jobs-per-second: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-frontend: mamba
cluster-status: status-scontrol.sh
cluster-cancel: scancel
max-status-checks-per-second: 10
